### ISSUE TITLE
Cannot move from field to field by pressing "Tab"

### ISSUE THREAD

**Issue by xauxatz** [taromero/swal-forms#18]
I can see that this works in the demo, but in my own project it doesn't work.
I've included swal and swal-forms packages.
The form otherwise works well.

**Comment by taromero** [comment]
@xauxatz: could you create a reproduction case in the form of a JsFiddle or similar?

**Comment by xauxatz** [comment]
Hi Tony

I've created a small Github Meteor project that you can download from 
here: https://github.com/xauxatz/test_swal_forms

It shows the same problem.

Thanks!

**Comment by taromero** [comment]
@xauxatz: take into account that the swal-forms' Meteor package is a separate repository which wraps swal-forms into Meteor's package structure. This Meteor package was using an old swal-forms version, and some changes regarding tab navigation have been made since.

I've just updated the Meteor package to use the current swal-forms version. Please test it again, using the latest version of the swal-forms' Meteor package (0.2.0).

**Comment by xauxatz** [comment]
Hi -

It works now, however, updating swal-forms to 0.2.0 required me to 
downgrade sweetalert to 0.5.0 (from 1.0.0) which is rather strange.

Can you make it so it works with the newest sweetalert as well?

**Comment by taromero** [comment]
I've just published meteor-swal-forms v0.3.0 with kevohagan:sweetalert's upgrade from 0.5.0 to 1.0.0.

**Comment by xauxatz** [comment]
Many thanks!
