### ISSUE TITLE
How to create dynamically checkboxs

### ISSUE THREAD

**Issue by geekdiv** [taromero/swal-forms#32]
Hello @taromero I want to create dynamically checkboxs using swal-forms 

```
var obj = JSON.parse(xhr.responseText).dup;
var checkBoxHtml = JSON.stringify(obj); // [{"name":"resume","value":"Bala.docx","type":"checkbox"},{"name":"resume","value":"Bala123.docx","type":"checkbox"}] 

swal.withForm({
    title: 'Resume Import',
    text: 'This has different types of inputs',
    showCancelButton: true,
    confirmButtonColor: '#DD6B55',
    confirmButtonText: 'Get form data!',
    closeOnConfirm: true,
    formFields: checkBoxHtml
}, function(isConfirm) {
    var selectedJsonString = JSON.stringify(this.swalForm);
    console.log("Selected Data  ::" + selectedJsonString);
});

```
I try above code but I got below error 
`Uncaught TypeError: this.formFields.map is not a function`

![2 1](https://cloud.githubusercontent.com/assets/12626079/22206146/0ad8c45c-e1a0-11e6-8534-4fda69fd982d.png)

but when I paste `checkBoxHtml` value (static checkbox) then it work fine instead of checkBoxHtml on `formFields`

please give your valuable suggestions how to resolve it. @taromero

**Comment by taromero** [comment]
"but when I paste checkBoxHtml value (static checkbox) then it work fine instead of checkBoxHtml on formFields" sorry I didn't understand this part.

This is failing because you are passing a string value to the "formFields" parameter, while it expects an array. Calling JSON.stringify is the problematic part here. If you need to do that for any reason, you would have to transform the string back into an object by calling JSON.parse, for this to work.

**Comment by geekdiv** [comment]
@taromero thank it's working now :) :+1:  my mistake is I pass JSON string instead of JSON object in formFields
